schema_version: 1

context:
  version: "0.11.2"

package:
  name: fps-jupyterlab
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-jupyterlab/fps_jupyterlab-${{ version }}.tar.gz
    sha256: 058264b7e5c25bd27e9f03d99d727b2e7cb691ae43eb62bb2c0316f8c2f79bb5

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0
    - jupyterlab-js >=4.4.2,<5

tests:
  - python:
      imports: fps_jupyterlab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/jupyterlab
  summary: An FPS plugin for the JupyterLab API

extra:
  recipe-maintainers:
    - davidbrochart
